name: Mule Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Universal environment variables for all steps inside this job
    env:
      MAVEN_USERNAME: "~~~Client~~~"
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
          
          # This maps directly to the <id> anypoint-id in your pom.xml
          server-id: "anypoint-id"
          
          # Defines the names of the environment variables Maven will look for
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      # The global env is safely active here, but ignored since it's just compiling
      - name: Build Package
        run: mvn clean package

      # Step 1: Inherits global MAVEN_USERNAME and MAVEN_PASSWORD
      - name: Deploy to Exchange
        run: mvn deploy

      # Step 2: Also inherits global MAVEN_USERNAME and MAVEN_PASSWORD
      - name: Deploy to Mule Runtime
        run: mvn mule:deploy
