name: Mule Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
          server-id: "anypoint-id"
          server-username: "~~~Client~~~"
          server-password: "4b3c316d01f14ce5813258d0105ffeed~?~4d0E9E3A93884c5Fb21Dcc6304b8750e"

      - name: Build Package
        run: mvn clean package

      - name: Deploy Artifact
        run: mvn deploy

      - name: Deploy to Mule Runtime
        run: mvn mule:deploy
